server:
  port: 9000
  context-path: /config

management:
  security:
    enabled: false
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/MagicCoderShow/SpringCloudConfig.git
          search-paths: data