eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
server:
  port: 9013
spring:
  application:
    name: service-produce
    
management:
  security:
    enabled: false