eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
server:
  port: 9012
spring:
  application:
    name: service-customer
    
management:
  security:
    enabled: false